version: '3.9'
services:
  web:
    image: aggarcia3/xcs-project-app-staging:push-master-latest
    ports:
      - 8080:8080
    networks:
      - app
    depends_on:
      - db
  db:
    image: mariadb:10.7
    environment:
      - MYSQL_DATABASE=dgss
      - MYSQL_USER=dgssuser
      - MYSQL_PASSWORD=dgsspass
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - app-db-data:/var/lib/mysql
    networks:
      - app
volumes:
  app-db-data:
networks:
  app:
